version: '3.9'
services:
  frontend:
    container_name: vuejs-docker
    build:
      context: ./vuejs
      dockerfile: ./Dockerfile
    ports:
    - 8080:8080
  backend:
    container_name: nestjs-docker
    build:
      context: ./nestjs
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000