version: '3.9'
services:
  frontend:
    container_name: vuejs-docker
    build:
      context: ./vuejs
      dockerfile: ./Dockerfile
    ports:
    - 8080:8080
    # volumes:
    # - .:/app
    # command: /bin/sh -c "cd vuejs && npm run preview"
  backend:
    container_name: nestjs-docker
    build:
      context: ./nestjs
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000