name: Trigger auto deployment for vue-nest-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/vue-nest-test-AutoDeployTrigger-03508622-8403-4c8b-8b35-d26a76b4f7fc.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.VUENESTTEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.VUENESTTEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.VUENESTTEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.VUENESTTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.VUENESTTEST_REGISTRY_PASSWORD }}
          containerAppName: vue-nest-test
          resourceGroup: Test-EU-West
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


